### PR TITLE
Fix duplicate output when more than 1 line (fixes #153)

### LINKED ISSUE #153: Using select with message longer than terminal width duplicates the message.
### Describe the bug
Using select with message longer than terminal width duplicates the message and breaks the UI.

prompts-bug

### To Reproduce
Just run this script in a relatively narrow terminal window:

```js
const prompts = require('prompts')

const runPrompt = async () => {
  const selected = await prompts(
    {
      type: 'select',
      name: 'template',
      message: 'What would you like to create in this directory?',
      choices: [
        { title: 'My Own Component', value: 'component' },
        { title: 'Function', value: 'function' },
        { title: 'API', value: 'api' },
        { title: 'Website', value: 'website' },
        { title: 'Realtime Application', value: 'realtime-app' },
        { title: 'Chat Application', value: 'chat-app' },
        { title: 'Websocket Backend', value: 'websocket-backend' }
      ],
      initial: 0
    },
    {
      onCancel: () => process.exit(0)
    }
  )
  console.log(selected)
}

runPrompt()


```

### Expected behavior
It should detect terminal width and adjust cursor automatically. It shouldn't duplicate the message.

### System

- OS: macOS 10.14.2
- Terminal: iTerm
- Node version: `v11.12.0`

### Additional context
Might be related to #89

### PR DESCRIPTION
**Pull request by DrunkenPoney**
Fixes #153

_Note:_ don't merge yet. I'll check the other prompt types too...

<hr>
<strong>Update:</strong> I've fixed the other prompt types. You can merge if you want.

### CODE REVIEW

**Comment by DrunkenPoney** [comment]
Verified prompt types:

- [ ] Autocomplete
- [ ] Autocomplete (multiselect)
- [ ] Confirm
- [ ] Date
- [ ] Multiselect
- [ ] Number
- [x] Select
- [ ] Text
- [ ] Toggle

**Comment by DrunkenPoney** [comment]
Done!

**Comment by terkelg** [comment]
Thank you dude!

**Comment by lumio** [comment]
Oh my! This really is a big one haha 😆 I'll look into that on the weekend! 👍

File: lib/elements/date.js [hunk 1]
```diff
@@ -27,16 +27,48 @@ const dfltLocales = {
...
  * @param {Object} opts Options
  * @param {String} opts.message Message
- * @param {Number} [opts.initial] Index of default value
- * @param {String} [opts.mask] The format mask
- * @param {object} [opts.locales] The date locales
- * @param {String} [opts.error] The error message shown on invalid value
- * @param {Function} [opts.validate] Function to validate the submitted value
- * @param {Stream} [opts.stdin] The Readable stream to listen to
- * @param {Stream} [opts.stdout] The Writable stream to write readline data to
+ * @param {Number} [opts.initial] Index
```
Comment (terkelg) [inline lib/elements/date.js]: Can you fix the formatting here?

File: lib/elements/prompt.js [hunk 2]
```diff
@@ -12,7 +12,7 @@ const color = require('kleur');
  * @param {Stream} [opts.stdout] The Writable stream to write readline data to
  */
 class Prompt extends EventEmitter {
-  constructor(opts={}) {
+  constructor(opts = {}) {
```
Comment (terkelg) [inline lib/elements/prompt.js]: Looks like there is some auto-formatting going on. Should we introduce something like prettier to avoid this in the future?

File: lib/elements/date.js (hunk 1 above)
Comment (terkelg) [inline lib/elements/date.js]: Can you fix the formatting here? Maybe it's a bug on GitHub?

image

File: lib/util/ansi.js [hunk 3]
```diff
@@ -0,0 +1,8 @@
+'use strict';
```
Comment (terkelg) [inline lib/util/ansi.js]: Should we add this to `sister-ansi` instead?

File: lib/elements/prompt.js (hunk 2 above)
Comment (lumio) [reply lib/elements/prompt.js]: Would be a good idea ... this would also allow to unify the code style

**Comment by lumio** [comment]
Other than the code style issue, everything looks fine :)

File: lib/elements/date.js (hunk 1 above)
Comment (DrunkenPoney) [reply lib/elements/date.js]: Fixed! Don't know why it did that. My formatting settings are setted so my IDE should not even touch the comments. That's weird.

File: lib/util/ansi.js (hunk 3 above)
Comment (DrunkenPoney) [reply lib/util/ansi.js]: I think I've already created a PR for that on sisteransi.

File: lib/elements/prompt.js (hunk 2 above)
Comment (DrunkenPoney) [reply lib/elements/prompt.js]: Fixed!

File: lib/util/ansi.js (hunk 3 above)
Comment (terkelg) [reply lib/util/ansi.js]: Awesome! I somehow missed that. It's merged now!

**Comment by terkelg** [comment]
Hyped to get this one published. I have merged your sisteransi PR in https://github.com/terkelg/sisteransi/pull/4 and published a new version. It should be ready to be used in Prompts

**Comment by DrunkenPoney** [comment]
@terkelg Done!

**Comment by DrunkenPoney** [comment]
I just realised that in the `index.js` file of sisteransi, the constant [`ESC`](https://en.wikipedia.org/wiki/ANSI_escape_code#Escape_sequences) is not really the ANSI's escape character but the [CSI (_Control Sequence Introducer_)](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_sequences). So actually the save and restore does not work cause they are not part of the control sequences. I'm fixing this.

https://github.com/terkelg/sisteransi/blob/a13a7e755f6dc657f556e5178489446dc1f5494b/src/index.js#L3

**Comment by DrunkenPoney** [comment]
I fixed sisteransi but I noticed something else... (See the note in the [PR](https://github.com/terkelg/sisteransi/pull/5))

**Comment by terkelg** [comment]
Awesome! 🚀 
Let's make sure the master branch is working correctly before we release a new version.
