### PR TITLE
Fix ALT+<key> prints undefined

### LINKED ISSUE #145: ALT + <key> prints `undefined`
### Description
I was looking for a way to do [this](https://github.com/terkelg/prompts/blob/d320cd78d409d0bef7c1928286abf6c5a2ba176c/lib/elements/autocomplete.js#L134), but I realized it wouldn't be possible with the <kbd>ctrl</kbd> key so I tried with <kbd>alt</kbd> instead and I found that pressing <kbd>alt</kbd> with any other letter key will print _undefined_.

### To Reproduce
Just press <kbd>alt</kbd>+_key_ on any prompt accepting user input like text or autocomplete.

### Expected behavior
Nothing!

### System
- OS: Linux
- Terminal: Linux terminal (bash)
- Node: v11.10.0

### PR DESCRIPTION
**Pull request by DrunkenPoney**
Fixes #145

### CODE REVIEW

**Comment by terkelg** [comment]
Thank you!

File: lib/util/action.js [hunk 1]
```diff
@@ -1,6 +1,8 @@
 'use strict';
 
 module.exports = (key, isSelect) => {
+  if (key.meta) return;
```
Comment (lumio) [inline lib/util/action.js]: The function returns `false` at the end. Shouldn't it also return `false` here? Or won't it have the needed effect?
If it should be as is, then I would approve it 😃

Comment (DrunkenPoney) [reply lib/util/action.js]: In fact, when nothing (or `undefined`) is returned the bell function is called and when `false` is returned it calls `this._(str, key)`.

Though, if you think it's better to return false instead of undefined I can easily change it.

https://github.com/terkelg/prompts/blob/0188d6a3d7f5ba95e94831de1f26cdfca7cb8ec3/lib/elements/prompt.js#L27-L36

**Comment by lumio** [comment]
Alright :D all good with me
